/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testQuote(){
        List<String> sampleTag = new LinkedList<>();
        sampleTag.add("sample tag");
        Quotes test = new Quotes(sampleTag, "Adison", "5 likes", "Random " );
        assertEquals("Quote tag should be the same.", sampleTag, test.getTags());
        assertEquals("Quote author should be the same.", "Adison", test.getAuthor());
        assertEquals("Quote likes should be the same.", "5 likes", test.getLikes());
        assertEquals("Quote text should be the same.", "Random ", test.getText());
    }

    public static final String FILE = "../app/src/test/resources/test.json";

    @Test
    public void testRandomQuote() throws FileNotFoundException {
        quotesRead test = new quotesRead(FILE);
        String expected = " “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to " +
                "find someone to love.” " + "\n- Marilyn Monroe";
        assertEquals("Should contain quotes", expected, test.getRandomQuote());
    }



}



