/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.FileNotFoundException;


public class App {

    public static final String FILE = "app/src/main/resources/recentquotes.json";

    public static void main(String[] args) throws FileNotFoundException {
        quotesRead qReader = new quotesRead(FILE);
        System.out.println(qReader.getRandomQuote());

    }


    
}
