/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import java.io.*;
import java.net.MalformedURLException;
import java.net.URL;


public class App {

    private static final String FILE = "app/src/main/resources/recentquotes.json";
    static  final quotesRead quotesRead = new quotesRead(FILE);

    public static void main(String[] args) throws IOException {
        quotesApiRead.getUrlQuote("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
    }



    }


